[package]
name = "ast_gen"
version = "0.1.0"
authors = ["Radoslav Mráz <radoslavmraz95@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.2"
rand = "0.7.0"
imageproc = "0.18.0"
structopt = "0.2.18"

[[bin]]
name = "ast_gen"
path = "bin/main.rs"